[project]
name = "mlopsbootcamp"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fastapi>=0.124.4",
    "matplotlib>=3.7.5",
    "mlflow>=2.17.2",
    "numpy>=1.24.4",
    "pandas>=2.0.3",
    "requests>=2.32.4",
    "scikit-learn>=1.3.2",
    "seaborn>=0.13.2",
    "streamlit>=1.40.1",
    "uvicorn>=0.33.0",
]

[dependency-groups]
dev = [
    "mypy>=1.14.1",
    "pytest>=8.3.5",
    "ruff>=0.15.13"

]

[tool.mypy]
python_version = "3.11"
files = ["src", "constants"]
explicit_package_bases = true
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "src.ModelTraining"
disable_error_code = ["assignment"]

[[tool.mypy.overrides]]
module = "src.ModelPredictions"
disable_error_code = ["call-arg"]

[[tool.mypy.overrides]]
module = "src.streamlit_app.*"
disable_error_code = ["import-untyped"]
